ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx-internal"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 150M
  hosts:
    - kibana.rgsndbx.aws.perion.com
elasticsearchHosts: "http://logs-master:9200"
